import {test, expect} from '@playwright/test';
import {readFileSync} from 'node:fs';

test('Excel 真實上傳、工作表／標頭確認、失效攔截與 Task 保存', async ({page, request}) => {
  expect((await (await request.get('/api/ready')).json()).execution_enabled).toBe(false);
  const project = await (await request.post('/api/projects', {data: {project_name: `Excel選擇-${Date.now()}`}})).json();
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`/#/projects/${project.project_id}/tasks/new`);
  await page.getByRole('textbox', {name: 'Task 名稱', exact: true}).fill('Excel 工作表確認驗收');
  await page.getByRole('textbox', {name: '需求描述', exact: true}).fill('只測合成 Excel 選擇與保存，不執行 ETL。');
  const bytes = Buffer.from(readFileSync(new URL('./fixtures/excel-selection.base64', import.meta.url), 'utf8').trim(), 'base64');
  await page.getByRole('button', {name: '選擇並上傳檔案', exact: true}).setInputFiles({name: 'synthetic.xlsx', mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', buffer: bytes});
  const panel = page.getByRole('region', {name: 'Excel 工作表與標頭確認'});
  const create = page.getByRole('button', {name: '建立 Task', exact: true});
  await expect(panel.getByLabel('Excel 工作表')).toHaveValue('');
  await expect(create).toBeDisabled();
  await panel.getByLabel('Excel 工作表').selectOption('明細');
  await panel.getByRole('button', {name: '解析並確認此工作表'}).click();
  await expect(panel.getByRole('alert')).toContainText('空白欄名');
  await expect(create).toBeDisabled();
  await panel.getByLabel('Excel 標頭列').fill('2');
  await panel.getByRole('button', {name: '解析並確認此工作表'}).click();
  await expect(panel.getByRole('status')).toContainText('已確認：明細，第 2 列標頭，2 個欄位');
  await expect(create).toBeEnabled();
  await panel.getByLabel('Excel 工作表').selectOption('重複欄');
  await expect(create).toBeDisabled();
  await panel.getByLabel('Excel 標頭列').fill('1');
  await panel.getByRole('button', {name: '解析並確認此工作表'}).click();
  await expect(panel.getByRole('alert')).toContainText('重複欄名');
  await expect(create).toBeDisabled();
  await panel.getByLabel('Excel 工作表').selectOption('明細');
  await panel.getByLabel('Excel 標頭列').fill('2');
  let release: () => void = () => {}, intercepted = false;
  const gate = new Promise<void>(resolve => {release = resolve});
  await page.route('**/api/task-sources/*/excel-profile', async route => {
    intercepted = true; await gate; await route.continue();
  });
  try {
    await panel.getByRole('button', {name: '解析並確認此工作表'}).click();
    await expect.poll(() => intercepted).toBe(true);
    await expect(panel.getByLabel('Excel 工作表')).toBeDisabled();
    await expect(panel.getByLabel('Excel 標頭列')).toBeDisabled();
    await expect(page.getByRole('button', {name: '取消全部 Task 草稿'})).toBeDisabled();
    await expect(create).toBeDisabled();
  } finally {release()}
  await expect(create).toBeEnabled();
  await page.unroute('**/api/task-sources/*/excel-profile');
  await page.setViewportSize({width: 390, height: 1000});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2)).toBe(true);
  await page.screenshot({path: test.info().outputPath('excel-confirmation.png'), fullPage: true});
  const response = page.waitForResponse(r => r.url().endsWith('/api/tasks') && r.request().method() === 'POST');
  await create.click();
  const saved = await response;
  expect(saved.status()).toBe(201);
  const task = await saved.json();
  const reloaded = await (await request.get(`/api/tasks/${task.id}`)).json();
  const source = reloaded.source_config.sources[0];
  expect(source.worksheet).toBe('明細');
  expect(source.header_row).toBe(2);
  expect(source.fields).toEqual([{name: '客戶編號', type: 'VARCHAR(32)'}, {name: '金額', type: 'DECIMAL(18,6)'}]);
  expect(source.excel_selection_v1.content_checksum).toBe(source.checksum);
  expect(source.excel_selection_v1.scope).toBe('INPUT_SELECTION_ONLY');
  expect(source).not.toHaveProperty('sample_rows');
  const unconfirmed = {...saved.request().postDataJSON(), creation_request_key: undefined};
  unconfirmed.source_config.sources[0].excel_selection_v1 = null;
  expect((await request.post('/api/tasks', {data: unconfirmed})).status()).toBe(422);
  const naming = await request.post(`/api/tasks/${task.id}/naming-contract/suggest`);
  expect(naming.status()).toBe(200);
  expect((await naming.json()).contract.columns.map((column: any) => column.source_name)).toEqual(['客戶編號', '金額']);
  expect((await (await request.get(`/api/tasks/${task.id}/runs`)).json()).runs).toEqual([]);
  await page.getByRole('tab', {name: '需求與規格', exact: true}).click();
  await page.reload();
  await expect(page.getByRole('heading', {name: '建立 Task 的完整設定'})).toBeVisible();
  const selection = page.getByRole('region', {name: '已保存的 Excel 來源選擇'});
  await expect(selection).toContainText('已確認：明細，第 2 列標頭');
  await selection.getByText('來源選擇指紋', {exact: true}).click();
  await expect(selection).toContainText(source.excel_selection_v1.profile_checksum);
  expect(errors).toEqual([]);
});
