import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';

test('真實中斷 Run：網站核對結案、API 保存重載及重複提交',async({page,request})=>{
 test.skip(process.env.WORKBENCH_REAL_RECONCILIATION!=='1','Explicit approval for the dedicated crashed test run required');
 const task=process.env.WORKBENCH_CRASH_TASK!,run=process.env.WORKBENCH_CRASH_RUN!,project=process.env.WORKBENCH_CRASH_PROJECT!;
 expect(task).toMatch(/^native-pilot-[a-f0-9]{32}$/);
 const bytes=await readFile(process.env.WORKBENCH_CRASH_EVIDENCE!);
 const evidence=JSON.parse(bytes.toString());
 expect(evidence.task_id).toBe(task);expect(evidence.run_id).toBe(run);
 expect(evidence.state).toBe('NEEDS_REVIEW');expect(evidence.outcome).toBe('HOP_RESULT_UNKNOWN');
 expect(evidence.rows).toEqual([['A','301.35','2']]);expect(evidence.write_events).toBe(1);
 const base=`/api/tasks/${task}/runs/${run}`;
 const original=await (await request.get(base)).json();
 expect(original.state).toBe('NEEDS_REVIEW');expect(original.outcome_code).toBe('HOP_RESULT_UNKNOWN');expect(original.write_started).toBe(true);
 expect((await (await request.get(base+'/reconciliation')).json()).status).toBe('AWAITING_RECONCILIATION');
 expect((await (await request.get('/api/ready')).json()).execution_enabled).toBe(false);
 await page.goto(`/#/projects/${project}/tasks/${task}/requirements`);
 const panel=page.getByRole('region',{name:'執行結果人工核對',exact:true});
 const save=panel.getByRole('button',{name:'保存人工核對並結案（不重跑）'});
 await expect(save).toBeDisabled();
 await panel.getByLabel('我已確認本次 Hop 程序停止').check();
 await panel.getByLabel('我已核對本次目標與寫入範圍，並保留查詢證據').check();
 await panel.getByLabel('核對時目標筆數').fill('1');
 await panel.getByLabel('選擇核對證據檔案').setInputFiles({name:'inspection.json',mimeType:'application/json',buffer:bytes});
 await panel.getByLabel('我確認只結束此次失敗／未知版本，不重跑，也不宣告成功').check();
 await expect(save).toBeEnabled();
 const posted=page.waitForResponse(r=>r.url().endsWith(base+'/reconciliation')&&r.request().method()==='POST');
 await save.click();const response=await posted;expect(response.status()).toBe(200);
 const payload=response.request().postDataJSON(),receipt=await response.json();
 expect(payload.evidence_sha256).toBe(createHash('sha256').update(bytes).digest('hex'));
 expect(receipt.status).toBe('CLOSED_WITHOUT_RETRY');expect(receipt.release_ready).toBe(false);
 await expect(panel.getByRole('status')).toContainText('已人工結案，未重跑');
 await page.reload();await expect(panel.getByRole('status')).toContainText('已人工結案');
 const repeated=await request.post(base+'/reconciliation',{data:payload});
 expect(repeated.status()).toBe(200);expect(await repeated.json()).toEqual(receipt);
 expect((await request.post(base+'/reconciliation',{data:{...payload,observed_row_count:2}})).status()).toBe(409);
 const after=await (await request.get(base)).json();
 expect(after.state).toBe('FAILED');expect(after.outcome_code).toBe(original.outcome_code);expect(after.write_started).toBe(true);
 expect(after.events.filter((e:any)=>e.event_type==='WRITE_STARTED')).toHaveLength(1);
 expect(after.events.filter((e:any)=>e.event_type==='OPERATOR_RECONCILED_WITHOUT_RETRY')).toHaveLength(1);
 await page.setViewportSize({width:390,height:900});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);
 await panel.screenshot({path:'test-results/crash-reconciliation-live.png'});
});
