import {test, expect} from '@playwright/test';
import {writeFile} from 'node:fs/promises';

test('真實規格：UI 建立保存核准 → PostgreSQL API 回讀 → 時間線（無模型／ETL）', async ({page, request}) => {
  test.skip(process.env.WORKBENCH_TEST_CONTROL_WORKER !== '1', 'Requires isolated deterministic CONTROL worker');
  await expect.poll(async () => {
    const response = await request.get('/api/ready');
    return response.ok() ? (await response.json()).status : `HTTP_${response.status()}`;
  }, {timeout:15000}).toBe('ready');
  expect((await (await request.get('/api/ready')).json()).execution_enabled).toBe(false);
  const original = (await (await request.get('/api/settings/groups')).json()).values.data_connections_targets;
  const suffix = Date.now();
  const profileId = `spec-live-${suffix}`;
  const connectionId = `spec-live-qa-${suffix}`;
  let taskId: string | undefined;
  try {
    expect((await request.put(`/api/settings/ai-profiles/${profileId}`, {data:{display_name:'規格真實UI控制流程測試',provider_type:'LITELLM_BEDROCK',region:'us-east-1',model_routes:{requirement_gate:'bedrock/synthetic',etl_specification:'bedrock/synthetic',qa_review:'bedrock/synthetic'},enabled:true}})).status()).toBe(200);
    expect((await request.put('/api/settings/groups/data_connections_targets', {data:{...original,etl_qa:{connection_id:connectionId,host:'synthetic-no-connection',port:5433,database:'synthetic',user:'synthetic'}}})).status()).toBe(200);
    const project = await (await request.post('/api/projects', {data:{project_name:`規格真實UI驗收-${suffix}`,default_ai_profile:profileId,default_connection:connectionId}})).json();
    const created = await request.post(`/api/projects/${project.project_id}/tasks`, {data:{name:'規格保存核准真實驗收',requirement:'按類別彙總金額大於100的資料，計算總額及筆數；此案例只測規格控制流程，不執行ETL。',source_config:{sources:[{type:'CSV',has_actual_data:false,fields:[{name:'類別',type:'VARCHAR(32)'},{name:'金額',type:'NUMERIC(12,2)'}]}],csv_input_contract_v1:{version:1,encoding:'UTF-8',delimiter:',',header:true,extra_columns:'REJECT'}},target_schema:'ai_sample',target_table:'spec_ui_only',target_config:{requirements_v1:{version:1,write_mode:'APPEND',date_scope:'ALL'}}}});
    expect(created.status()).toBe(201);
    taskId = (await created.json()).id;
    expect((await request.post(`/api/tasks/${taskId}/naming-contract/confirm`, {data:{columns:[{source_name:'類別',english_name:'category',vertica_type:'VARCHAR(32)'}]}})).status()).toBe(422);
    expect((await request.post(`/api/tasks/${taskId}/naming-contract/confirm`, {data:{columns:[
      {source_name:'類別',english_name:'category',vertica_type:'VARCHAR(32)'},
      {source_name:'金額',english_name:'amount',vertica_type:'NUMERIC(12,2)'},
      {source_name:'$metric.total',english_name:'total_amount',vertica_type:'NUMERIC(18,2)'},
      {source_name:'$metric.count',english_name:'row_count',vertica_type:'BIGINT'},
    ].map(column => ({...column,confidence:1,reason:'人工指定的合成測試命名'}))}})).status()).toBe(200);
    await page.goto(`/#/projects/${project.project_id}/tasks/${taskId}/requirements`);
    const versions = page.getByRole('region', {name:'執行準備版本',exact:true});
    await versions.getByRole('button',{name:'建立準備版本',exact:true}).click();
    await versions.getByLabel('我已核對本次需求及設定版本').check();
    await versions.getByRole('button',{name:'確認此版輸入',exact:true}).click();
    const run = (await (await request.get(`/api/tasks/${taskId}/runs`)).json()).runs[0];
    const base = `/api/tasks/${taskId}/runs/${run.run_id}`;
    await expect.poll(async () => (await (await request.get(base)).json()).gate_result?.status, {timeout:20000}).toBe('CHECKED');
    await versions.getByRole('button',{name:'重新載入版本',exact:true}).click();
    const panel = page.getByRole('region',{name:'ETL 規格版本',exact:true});
    await panel.getByRole('button',{name:'建立規格',exact:true}).click();
    const editor = panel.getByRole('region',{name:'編輯 ETL 規格'});
    await editor.getByRole('button',{name:'讀取已確認欄位'}).click();
    await expect(editor).toContainText('類別 → category');
    await editor.getByLabel('篩選方式').selectOption('FILTER');
    await editor.getByRole('button',{name:'新增篩選條件'}).click();
    await editor.getByLabel('條件欄位').selectOption('amount');
    await editor.getByLabel('比較方式').selectOption('GT');
    await editor.getByLabel('比較值（日期 YYYY-MM-DD，布林 true／false）').fill('100.00');
    await editor.getByLabel('以 category 分組').check();
    const sum = editor.locator('fieldset').filter({has:page.getByText('聚合輸出 total_amount',{exact:true})});
    await sum.getByLabel('聚合方式').selectOption('SUM');
    await sum.getByLabel('聚合來源欄位').selectOption('amount');
    const count = editor.locator('fieldset').filter({has:page.getByText('聚合輸出 row_count',{exact:true})});
    await count.getByLabel('聚合方式').selectOption('COUNT_ROWS');
    for (const name of ['category','total_amount','row_count']) await editor.getByRole('checkbox',{name,exact:true}).check();
    await editor.getByLabel('我已確認篩選、分組、聚合及輸出順序，保存為待核准規格。').check();
    await editor.getByRole('button',{name:'驗證並保存規格新版'}).click();
    await expect(panel).toContainText('已保存待核准規格');
    let rows = (await (await request.get(`${base}/specifications`)).json()).items;
    expect(rows).toHaveLength(1);
    expect(rows[0].spec_json.filters[0].constant).toEqual({type:'DECIMAL',value:'100.00'});
    expect(rows[0].approval_id).toBeNull();
    await panel.getByLabel('我已檢查目標、篩選、分組與輸出，確認此規格；這不是執行授權。').check();
    await panel.getByRole('button',{name:'核准此版規格'}).click();
    await expect(panel).toContainText('此規格核准目前有效');
    await page.reload();
    await panel.getByRole('button',{name:'載入規格版本'}).click();
    await expect(panel).toContainText('此規格核准目前有效');
    rows = (await (await request.get(`${base}/specifications`)).json()).items;
    expect(rows[0].approval_effective).toBe(true);
    await panel.getByRole('button',{name:'預覽 SDM 欄位對照'}).click();
    const sdm=panel.getByRole('region',{name:'SDM 欄位對照預覽'});
    await expect(sdm.getByRole('cell',{name:'total_amount',exact:true})).toBeVisible();
    await expect(sdm.getByRole('cell',{name:'金額 → amount',exact:true})).toBeVisible();
    await expect(sdm.getByRole('cell',{name:'整筆資料計數（不對應單一欄位）',exact:true})).toBeVisible();
    await expect(sdm).toContainText('尚未產生 Excel');
    await sdm.getByRole('button',{name:'產生／取得 SDM 候選 Excel'}).click();
    await expect(sdm.getByRole('status')).toContainText('候選 Excel 已保存');
    const downloaded=page.waitForEvent('download');
    await sdm.getByRole('button',{name:'下載 SDM 候選 Excel（非 Release）'}).click();
    const candidateFile=await downloaded;
    expect(candidateFile.suggestedFilename()).toMatch(/^SDM-candidate-[a-f0-9-]+\.xlsx$/);
    expect(await candidateFile.failure()).toBeNull();
    const savedCandidate=await request.post(`${base}/specifications/${rows[0].specification_id}/sdm-candidate`,{data:{content_checksum:rows[0].content_checksum}});
    expect(savedCandidate.status()).toBe(200);
    const sdmCandidate=await savedCandidate.json();
    expect(sdmCandidate.release_ready).toBe(false);
    expect(sdmCandidate).not.toHaveProperty('file_path');
    expect(candidateFile.suggestedFilename()).toContain(sdmCandidate.sdm_id);
    const bytes=await request.get(`${base}/sdm-candidates/${sdmCandidate.sdm_id}/download`);
    expect(bytes.status()).toBe(200);
    expect((await bytes.body()).subarray(0,2).toString()).toBe('PK');
    expect(bytes.headers()['x-content-sha256']).toBe(sdmCandidate.checksum);
    const sdmHistory=panel.getByRole('region',{name:'SDM 候選文件歷史',exact:true});
    await sdmHistory.getByRole('button',{name:'載入／重新整理 SDM 歷史'}).click();
    await expect(sdmHistory.getByRole('button',{name:'下載歷史候選 Excel（非 Release）'})).toHaveCount(1);
    const historicalDownload=page.waitForEvent('download');
    await sdmHistory.getByRole('button',{name:'下載歷史候選 Excel（非 Release）'}).click();
    const historicalFile=await historicalDownload;
    expect(await historicalFile.failure()).toBeNull();
    expect(historicalFile.suggestedFilename()).toBe(candidateFile.suggestedFilename());
    await sdmHistory.getByRole('button',{name:'載入／重新整理 SDM 歷史'}).click();
    await expect(sdmHistory.getByRole('button',{name:'下載歷史候選 Excel（非 Release）'})).toHaveCount(1);
    const rules=sdm.getByRole('region',{name:'SDM 轉換規則'});
    await expect(rules).toContainText('目標表：ai_sample.spec_ui_only');
    await expect(rules).toContainText('附加資料（APPEND）');
    await expect(rules.getByRole('listitem')).toContainText('amount 大於：100.00（DECIMAL）');
    await expect(rules).toContainText('分組欄位：category');
    await expect(rules).toContainText('EXCLUDE_UNKNOWN');
    await page.setViewportSize({width:390,height:1000});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);
    await page.setViewportSize({width:1440,height:1000});
    // The following are browser-only response variants, not persisted specifications or QA evidence.
    const sdmUrl=`${base}/specifications/${rows[0].specification_id}/sdm-preview`;
    const originalSdm=await(await request.get(sdmUrl)).json();
    let variant=structuredClone(originalSdm);
    let sdmFailure=false;
    await page.route(`**${sdmUrl}`,route=>sdmFailure?route.fulfill({status:503,json:{detail:'合成 SDM 讀取失敗'}}):route.fulfill({json:variant}));
    const refreshSdm=()=>sdm.getByRole('button',{name:'預覽 SDM 欄位對照'}).click();
    variant.document.filters=[];
    variant.document.aggregation=null;
    variant.document.mappings=[{position:1,target_column:'category',target_type:'VARCHAR(32)',operation:'DIRECT',source_columns:[{original_name:'類別',stream_name:'category'}]}];
    await refreshSdm();
    await expect(rules).toContainText('無篩選條件，保留全部來源資料。');
    await expect(rules).toContainText('不進行聚合');
    await expect(sdm.getByRole('cell',{name:'直接對應',exact:true})).toBeVisible();
    variant.document.filters=[{column:'category',operator:'IS_NULL',constant:null},{column:'category',operator:'IS_NOT_NULL',constant:null},{column:'category',operator:'EQ',constant:{type:'STRING',value:''}},{column:'enabled',operator:'EQ',constant:{type:'BOOLEAN',value:false}},{column:'amount',operator:'EQ',constant:{type:'INTEGER',value:0}}];
    await refreshSdm();
    await expect(rules.getByRole('listitem').nth(0)).toHaveText('category 是 NULL');
    await expect(rules.getByRole('listitem').nth(1)).toHaveText('category 不是 NULL');
    await expect(rules.getByRole('listitem').nth(2)).toContainText('空字串（長度 0）');
    await expect(rules.getByRole('listitem').nth(3)).toContainText('false（BOOLEAN）');
    await expect(rules.getByRole('listitem').nth(4)).toContainText('0（INTEGER）');
    variant=structuredClone(originalSdm);variant.document.aggregation.group_by=[];
    await refreshSdm();
    await expect(rules).toContainText('無分組欄位（整體聚合）');
    for(const mutate of [
      (v:any)=>{v.document.specification_checksum='0'.repeat(64)},
      (v:any)=>{v.document.filter_logic='ANY'},
      (v:any)=>{v.document.filter_null_policy='INCLUDE_UNKNOWN'},
      (v:any)=>{v.document.aggregation.null_policy='ZERO'},
      (v:any)=>{v.document.target.write_mode='TRUNCATE'},
      (v:any)=>{v.qa_passed=true},
      (v:any)=>{v.release_ready=true},
    ]){
      variant=structuredClone(originalSdm);mutate(variant);await refreshSdm();
      await expect(sdm.getByRole('alert')).toBeVisible();
      await expect(rules).toHaveCount(0);
      await expect(sdm.getByRole('table')).toHaveCount(0);
    }
    sdmFailure=true;await refreshSdm();
    await expect(sdm.getByRole('alert')).toContainText('合成 SDM 讀取失敗');
    await expect(rules).toHaveCount(0);
    sdmFailure=false;variant=structuredClone(originalSdm);await refreshSdm();
    await expect(rules).toContainText('目標表：ai_sample.spec_ui_only');
    await expect(sdm.getByRole('alert')).toHaveCount(0);
    await page.unroute(`**${sdmUrl}`);
    await panel.getByRole('button',{name:'檢查 Hop 編譯預覽'}).click();
    await expect(panel).toContainText('已產生編譯候選，尚未執行');
    await panel.getByText('查看 HWF 候選（非交付產物）',{exact:true}).click();
    await expect(panel.locator('pre').filter({hasText:'<workflow>'})).toContainText('${Internal.Workflow.Filename.Folder}/pipeline.hpl');
    await panel.getByText('Hop 候選指紋',{exact:true}).click();
    await expect(panel).toContainText('HWF：');
    await panel.getByText('查看 DDL 候選（未執行）',{exact:true}).click();
    const ddl=panel.locator('pre').filter({hasText:'CREATE TABLE'});
    await expect(ddl).toHaveText('CREATE TABLE "ai_sample"."spec_ui_only" (\n  "category" VARCHAR(32),\n  "total_amount" NUMERIC(18,2),\n  "row_count" BIGINT\n);\n');
    const previewResponse=await request.post(`${base}/specification/compile-preview`,{data:rows[0].spec_json});
    expect(previewResponse.status()).toBe(200);
    const candidate=await previewResponse.json();
    expect(candidate.ddl).toBe(await ddl.textContent());
    expect(candidate.execution_authorized).toBe(false);
    expect(candidate.release_ready).toBe(false);
    await expect(panel).toContainText(`DDL：${candidate.ddl_checksum}`);
    await panel.getByText('查看參數範本與環境需求',{exact:true}).click();
    await expect(panel.locator('pre').filter({hasText:'SOURCE_CSV='})).toHaveText(candidate.parameters);
    await expect(panel).toContainText(`參數範本指紋：${candidate.parameters_checksum}`);
    await page.setViewportSize({width:390,height:1000});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);
    await page.setViewportSize({width:1440,height:1000});
    await page.getByRole('tab',{name:'執行與 QA',exact:true}).click();
    const answer=page.getByRole('region',{name:'標準答案輸入',exact:true});
    await answer.getByRole('button',{name:'新增答案資料列'}).click();
    await answer.getByLabel('第 1 筆 category',{exact:true}).fill('A');
    await answer.getByLabel('第 1 筆 total_amount',{exact:true}).fill('301.35');
    await answer.getByLabel('第 1 筆 row_count',{exact:true}).fill('2');
    page.once('dialog',dialog=>dialog.dismiss());
    await page.getByRole('tab',{name:'概覽',exact:true}).click();
    await expect(answer.getByLabel('第 1 筆 total_amount',{exact:true})).toHaveValue('301.35');
    const failSave=`**${base}/specifications/${rows[0].specification_id}/oracles`;
    await page.route(failSave,route=>route.request().method()==='POST'?route.fulfill({status:503,json:{detail:'合成保存失敗'}}):route.continue());
    await answer.getByRole('button',{name:'保存答案版本',exact:true}).click();
    await expect(answer.getByRole('alert')).toContainText('保存或回讀未完成');
    await expect(answer.getByLabel('第 1 筆 total_amount',{exact:true})).toHaveValue('301.35');
    await expect(answer.getByRole('button',{name:'核准此答案版本'})).toHaveCount(0);
    await page.unroute(failSave);
    await answer.getByRole('button',{name:'保存答案版本',exact:true}).click();
    await expect(answer).toContainText('答案已保存並核對版本');
    const oracleBase=`${base}/specifications/${rows[0].specification_id}/oracles`;
    await page.setViewportSize({width:390,height:1000});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);
    await page.setViewportSize({width:1440,height:1000});
    let answers=(await(await request.get(oracleBase)).json()).items;
    expect(answers).toHaveLength(1);expect(answers[0].approval_recorded).toBe(false);
    await expect(answer.getByRole('button',{name:'核准此答案版本'})).toBeDisabled();
    await answer.getByLabel('我已確認上方答案內容與版本，核准供後續 QA 比對').check();
    await answer.getByRole('button',{name:'核准此答案版本'}).click();
    await expect(answer).toContainText('此答案版本的人工核准已保存');
    answers=(await(await request.get(oracleBase)).json()).items;
    expect(answers[0].approval_recorded).toBe(true);expect(answers[0].qa_passed).toBe(false);
    await answer.getByLabel('第 1 筆 total_amount',{exact:true}).fill('302.35');
    await expect(answer.getByRole('button',{name:'核准此答案版本'})).toHaveCount(0);
    await answer.getByRole('button',{name:'保存答案版本',exact:true}).click();
    await expect(answer).toContainText('答案已保存並核對版本');
    answers=(await(await request.get(oracleBase)).json()).items;
    expect(answers.map((a:any)=>a.version)).toEqual([2,1]);
    expect(answers.map((a:any)=>a.approval_recorded)).toEqual([false,true]);
    await page.reload();
    const answerHistory=page.getByRole('region',{name:'標準答案版本紀錄'});
    await expect(answerHistory.getByRole('heading',{name:'答案第 2 版',exact:true})).toBeVisible();
    await expect(answerHistory.getByText('曾人工核准；目前資格尚未評估')).toBeVisible();
    const oldAnswer=answerHistory.locator('article').filter({has:page.getByRole('heading',{name:'答案第 1 版',exact:true})});
    await oldAnswer.getByRole('button',{name:'查看答案內容'}).click();
    await expect(oldAnswer.getByRole('cell',{name:'301.35',exact:true})).toBeVisible();
    const newAnswer=answerHistory.locator('article').filter({has:page.getByRole('heading',{name:'答案第 2 版',exact:true})});
    await newAnswer.getByRole('button',{name:'查看答案內容'}).click();
    await expect(newAnswer.getByRole('cell',{name:'302.35',exact:true})).toBeVisible();
    await page.setViewportSize({width:390,height:1000});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);
    await oldAnswer.getByRole('button',{name:'關閉答案內容'}).click();
    await expect(oldAnswer.getByRole('cell',{name:'301.35',exact:true})).toHaveCount(0);
    await page.setViewportSize({width:1440,height:1000});
    await page.getByRole('tab',{name:'協作紀錄',exact:true}).click();
    const timeline = page.getByRole('region',{name:'版本協作紀錄'});
    await expect(timeline).toContainText('程式驗證後保存規格');
    await expect(timeline).toContainText('人工核准規格（非執行授權）');
    await expect(timeline).toContainText('程式工具保存 SDM 候選文件（非 Release）');
    const detail = await (await request.get(base)).json();
    expect(detail.write_started).toBe(false);
    expect(detail.events.filter((e:any) => e.event_type === 'SPECIFICATION_APPROVED')).toHaveLength(1);
    const sdmEvents=detail.events.filter((e:any)=>e.event_type==='SDM_CANDIDATE_SAVED');
    expect(sdmEvents).toHaveLength(1);
    expect(sdmEvents[0].event_context.sdm_id).toBe(sdmCandidate.sdm_id);
    expect(sdmEvents[0].event_context.checksum).toBe(sdmCandidate.checksum);
    expect((await (await request.get(`${base}/sa-invocation`)).json()).invocation).toBeNull();
    await page.screenshot({path:test.info().outputPath('real-specification-timeline.png'),fullPage:true});
    await page.getByRole('tab',{name:'交付',exact:true}).click();
    const delivery=page.getByRole('tabpanel',{name:'交付',exact:true});
    await expect(delivery.getByLabel('選擇 SDM 準備版本')).toHaveValue(run.run_id);
    const deliveryHistory=delivery.getByRole('region',{name:'SDM 候選文件歷史',exact:true});
    await deliveryHistory.getByRole('button',{name:'載入／重新整理 SDM 歷史'}).click();
    await expect(deliveryHistory.getByRole('button',{name:'下載歷史候選 Excel（非 Release）'})).toHaveCount(1);
    const deliveryDownload=page.waitForEvent('download');
    await deliveryHistory.getByRole('button',{name:'下載歷史候選 Excel（非 Release）'}).click();
    expect((await deliveryDownload).suggestedFilename()).toContain(sdmCandidate.sdm_id);
    await expect(delivery).toContainText('不提供正式 Release ZIP 下載');
    await expect(delivery.getByRole('heading',{name:'既有成果下載'})).toBeVisible();
    await page.setViewportSize({width:390,height:1000});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);
    const evidence = {project_id:project.project_id,task_id:taskId,run_id:run.run_id,specification:rows[0],oracles:answers,events:detail.events,write_started:detail.write_started,scope:'REAL_UI_API_POSTGRES_CONTROL_ONLY_NO_MODEL_NO_ETL'};
    await writeFile(test.info().outputPath('real-specification-evidence.json'),JSON.stringify(evidence,null,2));
    console.log('SPEC_LIVE_EVIDENCE',JSON.stringify({task_id:taskId,run_id:run.run_id,specification_id:rows[0].specification_id}));
  } finally {
    if (taskId) {
      const runs = (await (await request.get(`/api/tasks/${taskId}/runs`)).json()).runs || [];
      for (const run of runs) if (['QUEUED','NEEDS_REVIEW'].includes(run.state) && !run.write_started)
        expect((await request.post(`/api/tasks/${taskId}/runs/${run.run_id}/cancel`)).status()).toBe(200);
    }
    expect((await request.put('/api/settings/groups/data_connections_targets',{data:original})).status()).toBe(200);
  }
});
