import {test,expect} from '@playwright/test';

test('雙 CSV 正常建立、上傳與命名保存（真實 API；不執行 ETL）',async({page,request})=>{
  const projectResponse=await request.post('/api/projects',{data:{project_name:'雙CSV建立UI-'+Date.now()}});
  expect(projectResponse.status()).toBe(201);
  const project=await projectResponse.json();
  const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`/#/projects/${project.project_id}/tasks/new`);
  await page.getByRole('button',{name:'雙 CSV Join',exact:true}).click();
  await page.getByLabel('Task 名稱',{exact:true}).fill('雙CSV建立驗證');
  await page.getByLabel('需求描述',{exact:true}).fill('LEFT JOIN 依客戶編號保留左側所有資料，使用 APPEND 寫入測試表。');
  await page.getByLabel('左側 CSV',{exact:true}).setInputFiles({name:'left.csv',mimeType:'text/csv',buffer:Buffer.from('客戶編號,名稱\nA,left\n')});
  await expect(page.getByText('left.csv · 2 欄')).toBeVisible();
  await page.getByLabel('右側 CSV',{exact:true}).setInputFiles({name:'right.csv',mimeType:'text/csv',buffer:Buffer.from('客戶編號|名稱\nA|right\n')});
  await expect(page.getByText('right.csv · 2 欄')).toBeVisible();
  await expect(page.getByLabel('左側分隔符',{exact:true})).toHaveValue(',');
  await expect(page.getByLabel('右側分隔符',{exact:true})).toHaveValue('|');
  const submit=page.getByRole('button',{name:'建立雙 CSV Task',exact:true});
  await expect(submit).toBeDisabled();
  await expect(page.getByLabel('Join 類型',{exact:true})).toHaveValue('');
  await page.getByLabel('Join 類型',{exact:true}).selectOption('LEFT');
  await page.getByLabel('左側鍵值',{exact:true}).selectOption('客戶編號');
  await page.getByLabel('右側鍵值',{exact:true}).selectOption('客戶編號');
  await page.getByLabel('Vertica Table',{exact:true}).fill('ui_join_only');
  const confirm=page.getByRole('checkbox');
  await confirm.check();await expect(submit).toBeEnabled();
  await page.getByLabel('Join 類型',{exact:true}).selectOption('INNER');
  await expect(confirm).not.toBeChecked();await expect(submit).toBeDisabled();
  await page.getByLabel('Join 類型',{exact:true}).selectOption('LEFT');await confirm.check();
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+2)).toBe(true);
  const created=page.waitForResponse(response=>response.url().endsWith(`/api/projects/${project.project_id}/tasks`)&&response.request().method()==='POST');
  await submit.click();const response=await created;
  expect(response.status()).toBe(201);const task=await response.json();
  expect(task.source_config.csv_input_contracts_v1.sources['source.1'].delimiter).toBe('|');
  expect(task.target_config.join_contract_v1.joins[0].join_type).toBe('LEFT');
  await expect(page).toHaveURL(new RegExp(`/tasks/${task.id}(?:/|$)`));
  const suggestion=await request.post(`/api/tasks/${task.id}/naming-contract/suggest`);
  expect(suggestion.status()).toBe(200);const columns=(await suggestion.json()).contract.columns;
  expect(columns.map((column:any)=>column.source_name)).toEqual(['source.0.客戶編號','source.0.名稱','source.1.客戶編號','source.1.名稱']);
  expect((await request.post(`/api/tasks/${task.id}/naming-contract/confirm`,{data:{columns}})).status()).toBe(200);
  expect(errors).toEqual([]);
});
