import {test, expect} from '@playwright/test';
import {createHash} from 'node:crypto';

test('實際網站上傳 → 需求補正 → 共用儲存 Worker → PostgreSQL 證據（無模型／ETL）', async ({page, request}) => {
  test.skip(process.env.WORKBENCH_TEST_CONTROL_WORKER !== '1', 'Requires isolated CONTROL worker');
  page.setDefaultTimeout(10000);
  expect((await (await request.get('/api/ready')).json()).execution_enabled).toBe(false);
  const original = (await (await request.get('/api/settings/groups')).json()).values.data_connections_targets;
  const suffix = Date.now();
  const profile = `upload-live-${suffix}`, connection = `upload-qa-${suffix}`;
  let taskId: string | undefined;
  try {
    expect((await request.put(`/api/settings/ai-profiles/${profile}`, {data:{display_name:'上傳控制流程驗收',provider_type:'LITELLM_BEDROCK',region:'us-east-1',model_routes:{requirement_gate:'bedrock/synthetic',etl_specification:'bedrock/synthetic',qa_review:'bedrock/synthetic'},enabled:true}})).status()).toBe(200);
    expect((await request.put('/api/settings/groups/data_connections_targets', {data:{...original,etl_qa:{connection_id:connection,host:'synthetic-no-connection',port:5433,database:'synthetic',user:'synthetic'}}})).status()).toBe(200);
    const project = await (await request.post('/api/projects',{data:{project_name:`真實上傳驗收-${suffix}`,default_ai_profile:profile,default_connection:connection}})).json();
    await page.goto(`/#/projects/${project.project_id}/tasks/new`);
    await page.getByLabel('Task 名稱',{exact:true}).fill('實際上傳來源驗收');
    await page.getByLabel('需求描述',{exact:true}).fill('合成 CSV 來源驗收，保留全部資料，只檢查來源與版本，不執行 ETL。');
    const bytes = Buffer.from('customer_id,amount\n001,12.50\n002,20.00\n');
    const uploadResponse = page.waitForResponse(r=>r.url().endsWith('/api/task-sources/upload') && r.request().method()==='POST');
    await page.locator('input[type="file"]').setInputFiles({name:'source-proof.csv',mimeType:'text/csv',buffer:bytes});
    const uploaded = await uploadResponse;
    expect(uploaded.status()).toBe(200);
    const metadata = await uploaded.json();
    expect(metadata.checksum).toBe(createHash('sha256').update(bytes).digest('hex'));
    const createdResponse = page.waitForResponse(r=>r.url().endsWith('/api/tasks') && r.request().method()==='POST');
    await page.getByRole('button',{name:'建立 Task',exact:true}).click();
    const created = await createdResponse;
    expect(created.status()).toBe(201);
    const submitted = created.request().postDataJSON();
    expect(submitted.source_config.sources[0].size).toBe(bytes.length);
    expect(submitted.source_config.sources[0].upload_id).toBe(metadata.upload_id);
    taskId = (await created.json()).id;
    await page.getByRole('tab',{name:'需求與規格',exact:true}).click();
    const panel = page.getByRole('region',{name:'執行準備版本',exact:true});
    await panel.getByRole('button',{name:'建立準備版本',exact:true}).click();
    await panel.getByLabel('我已核對本次需求及設定版本').check();
    await panel.getByRole('button',{name:'確認此版輸入',exact:true}).click();
    const first = (await (await request.get(`/api/tasks/${taskId}/runs`)).json()).runs[0];
    await expect.poll(async()=> (await (await request.get(`/api/tasks/${taskId}/runs/${first.run_id}`)).json()).outcome_code,{timeout:20000}).toBe('REQUIREMENT_NEEDS_INPUT');
    await panel.getByRole('button',{name:'重新載入版本'}).click();
    await panel.getByRole('button',{name:'補正需求並建立新版',exact:true}).click();
    const form = panel.getByRole('form',{name:'需求補正'});
    await form.getByLabel('目標 Schema').fill('ai_sample');
    await form.getByLabel('目標 Table').fill('upload_control_only');
    await form.getByRole('combobox',{name:'寫入模式',exact:true}).selectOption('APPEND');
    await form.getByRole('combobox',{name:'資料期間',exact:true}).selectOption('ALL');
    await form.getByRole('button',{name:'設定 CSV 輸入契約',exact:true}).click();
    await form.getByRole('combobox',{name:'CSV 編碼',exact:true}).selectOption('UTF-8');
    await form.getByRole('combobox',{name:'CSV 分隔符號',exact:true}).selectOption(',');
    await form.getByRole('combobox',{name:'CSV 標題列',exact:true}).selectOption('true');
    await form.getByRole('combobox',{name:'CSV 額外欄位',exact:true}).selectOption('REJECT');
    await form.getByRole('button',{name:'保存補正並建立新版'}).click();
    await panel.getByLabel('我已核對本次需求及設定版本').check();
    await panel.getByRole('button',{name:'確認此版輸入',exact:true}).click();
    const child = (await (await request.get(`/api/tasks/${taskId}/runs`)).json()).runs[0];
    expect(child.parent_run_id).toBe(first.run_id);
    const url = `/api/tasks/${taskId}/runs/${child.run_id}`;
    await expect.poll(async()=> (await (await request.get(url)).json()).outcome_code,{timeout:20000}).toBe('PIPELINE_NOT_READY');
    const detail = await (await request.get(url)).json();
    const evidence = detail.gate_result.source_evidence[0];
    expect(evidence.status).toBe('UPLOAD_BYTES_VERIFIED');
    expect(evidence.content_checksum).toBe(metadata.checksum);
    expect(evidence.byte_count).toBe(bytes.length);
    expect(evidence.csv.complete).toBe(true);
    expect(evidence.csv.records_checked).toBe(2);
    expect(detail.write_started).toBe(false);
    expect((await (await request.get(`${url}/sa-invocation`)).json()).invocation).toBeNull();
    await panel.getByRole('button',{name:'重新載入版本'}).click();
    await expect(panel.getByRole('region',{name:'初步需求檢查結果'})).toBeVisible();
    const sourcePanel = panel.getByRole('region',{name:'來源檔案驗證證據'});
    await expect(sourcePanel).toContainText('已核對檔案大小：39 bytes');
    await expect(sourcePanel).toContainText('已檢查資料記錄：2；掃描完整');
    await sourcePanel.getByText('查看內容指紋（SHA-256）',{exact:true}).click();
    await expect(sourcePanel).toContainText(metadata.checksum);
    await page.setViewportSize({width:390,height:1000});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth + 2)).toBe(true);
    await page.screenshot({path:test.info().outputPath('upload-gate.png'),fullPage:true});
    await panel.getByRole('button',{name:'補正需求並建立新版',exact:true}).click();
    const replacementForm = panel.getByRole('form',{name:'需求補正'});
    const replacementPanel = replacementForm.getByRole('group',{name:'更換 CSV 來源'});
    const newBytes = Buffer.from('customer_id,amount\n003,99.00\n');
    await replacementPanel.getByLabel('新 CSV 檔案').setInputFiles({name:'replacement.csv',mimeType:'text/csv',buffer:newBytes});
    await expect(replacementPanel).toContainText('replacement.csv');
    await expect(replacementForm.getByRole('button',{name:'保存補正並建立新版'})).toBeDisabled();
    await replacementPanel.getByRole('button',{name:'取消換檔，保留原來源'}).click();
    await expect(replacementForm.getByRole('button',{name:'保存補正並建立新版'})).toBeEnabled();
    await replacementPanel.getByLabel('新 CSV 檔案').setInputFiles({name:'replacement.csv',mimeType:'text/csv',buffer:newBytes});
    await replacementPanel.getByLabel('我已核對新檔案與欄位，確認此修訂改用新 CSV').check();
    const revisionResponse=page.waitForResponse(r=>r.url().endsWith(`/api/tasks/${taskId}/runs/${child.run_id}/revisions`)&&r.request().method()==='POST');
    await replacementForm.getByRole('button',{name:'保存補正並建立新版'}).click();
    const revisionSaved=await revisionResponse;
    expect(revisionSaved.status()).toBe(201);
    const replaced = (await (await request.get(`/api/tasks/${taskId}/runs`)).json()).runs[0];
    // The UI reloads immediately after commit; inspect authoritative persisted state
    // rather than a browser response body discarded by that navigation.
    expect(replaced.run_id).not.toBe(child.run_id);
    expect(replaced.parent_run_id).toBe(child.run_id);
    const replacementUrl = `/api/tasks/${taskId}/runs/${replaced.run_id}`;
    expect((await (await request.get(replacementUrl)).json()).approval).toBeNull();
    await panel.getByLabel('我已核對本次需求及設定版本').check();
    await panel.getByRole('button',{name:'確認此版輸入',exact:true}).click();
    await expect.poll(async()=> (await (await request.get(replacementUrl)).json()).outcome_code,{timeout:20000}).toBe('PIPELINE_NOT_READY');
    const replacementDetail = await (await request.get(replacementUrl)).json();
    expect(replacementDetail.gate_result.source_evidence[0].content_checksum).toBe(createHash('sha256').update(newBytes).digest('hex'));
    const previous = await (await request.get(url)).json();
    expect(previous.gate_result.source_evidence[0].content_checksum).toBe(metadata.checksum);
    expect(previous.approval.decision).toBe('APPROVE');
    expect(previous.outcome_code).toBe('SUPERSEDED_BY_REVISION');
    console.log('REPLACEMENT_LIVE_EVIDENCE',JSON.stringify({task_id:taskId,parent:child.run_id,run_id:replaced.run_id}));
    console.log('UPLOAD_LIVE_EVIDENCE',JSON.stringify({task_id:taskId,run_id:child.run_id,...evidence}));
  } finally {
    if(taskId){
      const runs = (await (await request.get(`/api/tasks/${taskId}/runs`)).json()).runs || [];
      for(const run of runs) if(['QUEUED','NEEDS_REVIEW'].includes(run.state) && !run.write_started)
        expect((await request.post(`/api/tasks/${taskId}/runs/${run.run_id}/cancel`)).status()).toBe(200);
    }
    expect((await request.put('/api/settings/groups/data_connections_targets',{data:original})).status()).toBe(200);
  }
});
