"""Safe failure vocabulary; never publish exception messages or model text."""
from pydantic import ValidationError

FAILURE_CODES = frozenset({
    'DEVELOPER_OUTCOME_UNKNOWN', 'DEVELOPER_SCHEMA_INVALID',
    'DEVELOPER_SPECIFICATION_INVALID', 'DEVELOPER_EVIDENCE_INVALID',
    'DEVELOPER_JOIN_EVIDENCE_REQUIRED', 'DEVELOPER_CONTEXT_CHANGED',
    'DEVELOPER_CONTEXT_VERSION_CHANGED', 'DEVELOPER_CONTEXT_VERSION_MISMATCH',
    'DEVELOPER_TRACE_BINDING_CHANGED', 'DEVELOPER_TRACE_INVALID',
    'DEVELOPER_NATIVE_USAGE_INVALID', 'DEVELOPER_DISPATCH_CLAIM_EXPIRED_OR_LOST',
    'DEVELOPER_CLAIM_LOST', 'LOCAL_DEVELOPER_BRIDGE_UNAVAILABLE',
    'LOCAL_DEVELOPER_BRIDGE_FAILED', 'LOCAL_DEVELOPER_REQUEST_FAILED',
    'COPILOT_NOT_INSTALLED', 'COPILOT_SAFE_ENTRYPOINT_MISSING',
    'COPILOT_EXPLICIT_MODEL_REQUIRED', 'COPILOT_MCP_CONFIG_UNREADABLE',
    'COPILOT_BYOK_NOT_ALLOWED', 'COPILOT_CONTEXT_BINDING_REQUIRED',
    'COPILOT_OUTCOME_UNKNOWN_TIMEOUT', 'COPILOT_CALL_FAILED_OR_OUTPUT_TOO_LARGE',
    'COPILOT_OUTPUT_INCOMPLETE', 'COPILOT_MODEL_MISMATCH',
    'COPILOT_TOOL_POLICY_VIOLATION', 'COPILOT_OUTPUT_SCHEMA_INVALID',
})
FAILURE_STAGES = frozenset({'CLAIM_CHECK', 'MODEL_CALL', 'RESULT_CHECK', 'RESULT_PERSISTENCE', 'UNRECORDED'})


def safe_code(error):
    if isinstance(error, ValidationError):
        return 'DEVELOPER_SCHEMA_INVALID'
    code = str(error)
    return code if isinstance(error, ValueError) and code in FAILURE_CODES else 'DEVELOPER_OUTCOME_UNKNOWN'


def failure_summary(code=None, stage=None):
    return {'error_code': code if isinstance(code, str) and code in FAILURE_CODES else 'DEVELOPER_OUTCOME_UNKNOWN',
            'failure_stage': stage if isinstance(stage, str) and stage in FAILURE_STAGES else 'UNRECORDED',
            'automatic_retry': False}
