from __future__ import annotations
import hashlib,json,os,re,subprocess,time,uuid
from pathlib import Path
from xml.etree import ElementTree as ET
from xml.sax.saxutils import escape
import psycopg
from psycopg import sql
from .hop_generation_rules import generation_plan,validate_pipeline_graph
from .sample_data import _vertica_type

ROOT=Path(__file__).resolve().parents[2]
STEPS_BASE='''<description/><distribute>Y</distribute><custom_distribution/><copies>1</copies><partitioning><method>none</method><schema_name/></partitioning>'''

def _target_type(task:dict):return (task.get('target_config',{}).get('type') or task.get('target') or 'POSTGRESQL').upper()

def _apply_target(xml:str,task:dict):
 if _target_type(task)!='VERTICA':return xml
 xml=xml.replace('PostgreSQL Output','Vertica Output').replace('-postgresql</name>','-vertica</name>')
 marker='<connection>ai-agents-poc</connection>'
 if marker in xml:
  head,tail=xml.rsplit(marker,1);xml=head+'<connection>vertica-poc</connection>'+tail
 return xml

def _field_type(name:str):
 if name=='customer_id' or name.endswith('_id'):return 'Integer',''
 if name.endswith('_date'):return 'Date','yyyy-MM-dd'
 if name.startswith('is_'):return 'Boolean',''
 return 'String',''

def _hop_encoding(value:str):
 normalized=(value or 'UTF-8').strip().lower().replace('_','-')
 return {'utf-8-sig':'UTF-8','utf8-sig':'UTF-8','utf8':'UTF-8','big5':'Big5'}.get(normalized,value or 'UTF-8')

def build_hpl(task:dict,columns:list[str]):
 if task.get('category')=='STAGE' and str(task.get('target_config',{}).get('stage_mode','NORMAL')).upper() in ('EXTERNAL','FLEX'):return build_stage_hwf(task,columns)
 if task['source']=='POSTGRESQL_TABLE':return build_postgres_hpl(task,columns)
 if task['source'] in ('VERTICA','MIXED') and task['source_config'].get('query'):return build_vertica_query_hpl(task,columns)
 if task['source_config'].get('aggregation'):return build_csv_aggregate_hpl(task,columns)
 task_dir=ROOT/'hop-project'/'pipelines'/task['id'];task_dir.mkdir(parents=True,exist_ok=True)
 existing=list(task_dir.glob('pipeline-v*.hpl'));version=max([int(p.stem.rsplit('v',1)[1]) for p in existing]+[0])+1
 path=task_dir/f'pipeline-v{version}.hpl';source=escape(task['source_config']['file_path']);delimiter=escape(task['source_config'].get('delimiter',','));encoding=escape(_hop_encoding(task['source_config'].get('encoding','UTF-8')))
 fields=''.join(f'<field><name>{escape(c)}</name><type>{_field_type(c)[0]}</type><format>{_field_type(c)[1]}</format><currency/><decimal>.</decimal><group>,</group><length>-1</length><precision>-1</precision><trim_type>both</trim_type></field>' for c in columns)
 mappings=''.join(f'<field><column_name>{escape(c)}</column_name><stream_name>{escape(c)}</stream_name></field>' for c in columns)
 target_schema=escape(task['target_config']['schema']);target_table=escape(task['target_config']['table'])
 xml=f'''<?xml version="1.0" encoding="UTF-8"?>
<pipeline><info><name>{escape(task['id'])}-csv-postgresql</name><name_sync_with_filename>N</name_sync_with_filename><description>Generated by Developer Agent</description><extended_description/><pipeline_version>{version}</pipeline_version><pipeline_type>Normal</pipeline_type><parameters></parameters><capture_transform_performance>N</capture_transform_performance><transform_performance_capturing_delay>1000</transform_performance_capturing_delay><transform_performance_capturing_size_limit>100</transform_performance_capturing_size_limit><created_user>ai-agents-poc</created_user><created_date>2026/08/05 00:00:00.000</created_date><modified_user>ai-agents-poc</modified_user><modified_date>2026/08/05 00:00:00.000</modified_date><key_for_session_key/><is_key_private>N</is_key_private></info><notepads></notepads>
<order><hop><from>Read CSV</from><to>First 10 rows</to><enabled>Y</enabled></hop><hop><from>First 10 rows</from><to>PostgreSQL Output</to><enabled>Y</enabled></hop></order>
<transform><name>Read CSV</name><type>CSVInput</type>{STEPS_BASE}<filename>{source}</filename><filename_field/><rownum_field>row_number</rownum_field><include_filename>N</include_filename><separator>{delimiter}</separator><enclosure>"</enclosure><header>Y</header><buffer_size>50000</buffer_size><lazy_conversion>N</lazy_conversion><add_filename_result>N</add_filename_result><parallel>N</parallel><newline_possible>N</newline_possible><encoding>{encoding}</encoding><fields>{fields}</fields><attributes/><GUI><xloc>80</xloc><yloc>160</yloc></GUI></transform>
<transform><name>First 10 rows</name><type>FilterRows</type>{STEPS_BASE}<send_true_to/><send_false_to/><compare><condition><negated>N</negated><leftvalue>row_number</leftvalue><function>&lt;=</function><rightvalue/><value><name>constant</name><type>Integer</type><text>10</text><length>-1</length><precision>0</precision><isnull>N</isnull><mask>####0;-####0</mask></value></condition></compare><attributes/><GUI><xloc>280</xloc><yloc>160</yloc></GUI></transform>
<transform><name>PostgreSQL Output</name><type>TableOutput</type>{STEPS_BASE}<commit>10</commit><connection>ai-agents-poc</connection><fields>{mappings}</fields><ignore_errors>N</ignore_errors><partitioning_daily>N</partitioning_daily><partitioning_enabled>N</partitioning_enabled><partitioning_monthly>N</partitioning_monthly><return_keys>N</return_keys><schema>{target_schema}</schema><specify_fields>Y</specify_fields><table>{target_table}</table><tablename_in_field>N</tablename_in_field><tablename_in_table>Y</tablename_in_table><truncate>N</truncate><use_batch>Y</use_batch><attributes/><GUI><xloc>500</xloc><yloc>160</yloc></GUI></transform>
<transform_error_handling></transform_error_handling><attributes/></pipeline>'''
 xml=_apply_target(xml,task);path.write_text(xml,encoding='utf-8');checksum=hashlib.sha256(path.read_bytes()).hexdigest()
 return {'path':str(path),'version':version,'checksum':checksum,'size':path.stat().st_size,'columns':columns,'transforms':['CSVInput','FilterRows','TableOutput'],'generation_plan':generation_plan(task)}

def build_csv_aggregate_hpl(task:dict,columns:list[str]):
 cfg=task['source_config'];agg=cfg['aggregation'];group=_safe_ident(agg['group_by']);calc=agg['calculation'];calc_name=_safe_ident(calc['name']);field_a=_safe_ident(calc['field_a']);field_b=_safe_ident(calc['field_b']);sum_fields=agg['sum_fields']
 for required in (group,field_a,field_b,*[x['subject'] for x in sum_fields]):
  if required not in columns and required!=calc_name:raise ValueError(f'Aggregation field not found: {required}')
 task_dir=ROOT/'hop-project'/'pipelines'/task['id'];task_dir.mkdir(parents=True,exist_ok=True);existing=list(task_dir.glob('pipeline-v*.hpl'));version=max([int(p.stem.rsplit('v',1)[1]) for p in existing]+[0])+1;path=task_dir/f'pipeline-v{version}.hpl'
 source=escape(cfg['file_path']);delimiter=escape(cfg.get('delimiter',','));encoding=escape(_hop_encoding(cfg.get('encoding','UTF-8')));types=cfg.get('field_types') or {}
 field_formats=cfg.get('field_formats') or {}
 def input_field(c:str):
  field_type=types.get(c,_field_type(c)[0]);field_format=field_formats.get(c) or ('yyyy-MM-dd' if field_type=='Date' else _field_type(c)[1])
  return f'<field><name>{escape(c)}</name><type>{escape(field_type)}</type><format>{escape(field_format)}</format><currency/><decimal>.</decimal><group>,</group><length>-1</length><precision>-1</precision><trim_type>both</trim_type></field>'
 fields=''.join(input_field(c) for c in columns)
 module_path=None
 if cfg.get('module'):
  module_path=task_dir/f'calculation-module-v{version}.hpl'
  module_fields=''.join(f'<field><name>{escape(c)}</name><type>{escape(types.get(c,_field_type(c)[0]))}</type><length>-1</length><precision>-1</precision></field>' for c in columns)
  module_xml=f'''<?xml version="1.0" encoding="UTF-8"?><pipeline><info><name>{escape(task['id'])}-calculation-module</name><name_sync_with_filename>N</name_sync_with_filename><description>Reusable calculation module generated from transfer-project patterns</description><extended_description/><pipeline_version>{version}</pipeline_version><pipeline_type>Normal</pipeline_type><parameters></parameters><capture_transform_performance>N</capture_transform_performance><transform_performance_capturing_delay>1000</transform_performance_capturing_delay><transform_performance_capturing_size_limit>100</transform_performance_capturing_size_limit><created_user>ai-agents-poc</created_user><created_date>2026/08/12 00:00:00.000</created_date><modified_user>ai-agents-poc</modified_user><modified_date>2026/08/12 00:00:00.000</modified_date><key_for_session_key/><is_key_private>N</is_key_private></info><notepads></notepads><order><hop><from>MODULE_INPUT</from><to>Calculate Line Amount</to><enabled>Y</enabled></hop><hop><from>Calculate Line Amount</from><to>MODULE_OUTPUT</to><enabled>Y</enabled></hop></order>
<transform><name>MODULE_INPUT</name><type>MappingInput</type>{STEPS_BASE}<fields>{module_fields}</fields><attributes/><cluster_schema/><GUI><xloc>80</xloc><yloc>160</yloc><draw>Y</draw></GUI></transform>
<transform><name>Calculate Line Amount</name><type>Calculator</type>{STEPS_BASE}<failIfNoFile>Y</failIfNoFile><calculation><calc_type>MULTIPLY</calc_type><field_a>{field_a}</field_a><field_b>{field_b}</field_b><field_name>{calc_name}</field_name><remove>N</remove><value_length>14</value_length><value_precision>2</value_precision><value_type>Number</value_type></calculation><attributes/><GUI><xloc>300</xloc><yloc>160</yloc><draw>Y</draw></GUI></transform>
<transform><name>MODULE_OUTPUT</name><type>MappingOutput</type>{STEPS_BASE}<attributes/><cluster_schema/><GUI><xloc>520</xloc><yloc>160</yloc><draw>Y</draw></GUI></transform><transform_error_handling></transform_error_handling><attributes/></pipeline>'''
  module_path.write_text(module_xml,encoding='utf-8')
  connectors=''.join(f'<connector><parent>{escape(c)}</parent><child>{escape(c)}</child></connector>' for c in columns)
  calculation_transform=f'''<transform><name>Calculate Line Amount</name><type>SimpleMapping</type>{STEPS_BASE}<specification_method>rep_name</specification_method><trans_object_id/><filename>{escape(str(module_path))}</filename><mappings><input><mapping><input_transform/><output_transform/><main_path>Y</main_path><rename_on_output>N</rename_on_output><description/>{connectors}</mapping></input><output><mapping><input_transform/><output_transform/><main_path>Y</main_path><rename_on_output>N</rename_on_output><description/></mapping></output><parameters><inherit_all_vars>Y</inherit_all_vars></parameters></mappings><allow_multiple_input>Y</allow_multiple_input><allow_multiple_output>Y</allow_multiple_output><attributes/><cluster_schema/><remotesteps><input></input><output></output></remotesteps><GUI><xloc>410</xloc><yloc>160</yloc><draw>Y</draw></GUI><runConfiguration/></transform>'''
 else:
  calculation_transform=f'''<transform><name>Calculate Line Amount</name><type>Calculator</type>{STEPS_BASE}<failIfNoFile>Y</failIfNoFile><calculation><calc_type>MULTIPLY</calc_type><field_a>{field_a}</field_a><field_b>{field_b}</field_b><field_name>{calc_name}</field_name><remove>N</remove><value_length>14</value_length><value_precision>2</value_precision><value_type>Number</value_type></calculation><attributes/><GUI><xloc>410</xloc><yloc>160</yloc></GUI></transform>'''
 output_columns=[group]+[x['name'] for x in sum_fields];mappings=''.join(f'<field><column_name>{escape(c)}</column_name><stream_name>{escape(c)}</stream_name></field>' for c in output_columns);aggregates=''.join(f'<field><aggregate>{escape(x["name"])}</aggregate><subject>{escape(x["subject"])}</subject><type>SUM</type><valuefield/></field>' for x in sum_fields)
 target_schema=escape(task['target_config']['schema']);target_table=escape(task['target_config']['table'])
 xml=f'''<?xml version="1.0" encoding="UTF-8"?><pipeline><info><name>{escape(task['id'])}-csv-aggregate-postgresql</name><name_sync_with_filename>N</name_sync_with_filename><description>CSV calculation and grouped aggregation</description><extended_description/><pipeline_version>{version}</pipeline_version><pipeline_type>Normal</pipeline_type><parameters></parameters><capture_transform_performance>N</capture_transform_performance><transform_performance_capturing_delay>1000</transform_performance_capturing_delay><transform_performance_capturing_size_limit>100</transform_performance_capturing_size_limit><created_user>ai-agents-poc</created_user><created_date>2026/08/06 00:00:00.000</created_date><modified_user>ai-agents-poc</modified_user><modified_date>2026/08/06 00:00:00.000</modified_date><key_for_session_key/><is_key_private>N</is_key_private></info><notepads></notepads>
<order><hop><from>Read Sales CSV</from><to>First 10 rows</to><enabled>Y</enabled></hop><hop><from>First 10 rows</from><to>Calculate Line Amount</to><enabled>Y</enabled></hop><hop><from>Calculate Line Amount</from><to>Sort by Category</to><enabled>Y</enabled></hop><hop><from>Sort by Category</from><to>Group and Sum</to><enabled>Y</enabled></hop><hop><from>Group and Sum</from><to>PostgreSQL Output</to><enabled>Y</enabled></hop></order>
<transform><name>Read Sales CSV</name><type>CSVInput</type>{STEPS_BASE}<filename>{source}</filename><filename_field/><rownum_field>row_number</rownum_field><include_filename>N</include_filename><separator>{delimiter}</separator><enclosure>"</enclosure><header>Y</header><buffer_size>50000</buffer_size><lazy_conversion>N</lazy_conversion><add_filename_result>N</add_filename_result><parallel>N</parallel><newline_possible>N</newline_possible><encoding>{encoding}</encoding><fields>{fields}</fields><attributes/><GUI><xloc>60</xloc><yloc>160</yloc></GUI></transform>
<transform><name>First 10 rows</name><type>FilterRows</type>{STEPS_BASE}<send_true_to/><send_false_to/><compare><condition><negated>N</negated><leftvalue>row_number</leftvalue><function>&lt;=</function><rightvalue/><value><name>constant</name><type>Integer</type><text>10</text><length>-1</length><precision>0</precision><isnull>N</isnull><mask>####0;-####0</mask></value></condition></compare><attributes/><GUI><xloc>230</xloc><yloc>160</yloc></GUI></transform>
{calculation_transform}
<transform><name>Sort by Category</name><type>SortRows</type>{STEPS_BASE}<directory>${{java.io.tmpdir}}</directory><prefix>csv_group</prefix><sort_size>1000000</sort_size><free_memory/><compress>N</compress><compress_variable/><unique_rows>N</unique_rows><fields><field><name>{group}</name><ascending>Y</ascending><case_sensitive>N</case_sensitive><collator_enabled>N</collator_enabled><collator_strength>0</collator_strength><presorted>N</presorted></field></fields><attributes/><GUI><xloc>590</xloc><yloc>160</yloc></GUI></transform>
<transform><name>Group and Sum</name><type>GroupBy</type>{STEPS_BASE}<all_rows>N</all_rows><ignore_aggregate>N</ignore_aggregate><field_ignore/><directory>${{java.io.tmpdir}}</directory><prefix>grp</prefix><add_linenr>N</add_linenr><linenr_fieldname/><give_back_row>N</give_back_row><group><field><name>{group}</name></field></group><fields>{aggregates}</fields><attributes/><GUI><xloc>770</xloc><yloc>160</yloc></GUI></transform>
<transform><name>PostgreSQL Output</name><type>TableOutput</type>{STEPS_BASE}<commit>10</commit><connection>ai-agents-poc</connection><fields>{mappings}</fields><ignore_errors>N</ignore_errors><partitioning_daily>N</partitioning_daily><partitioning_enabled>N</partitioning_enabled><partitioning_monthly>N</partitioning_monthly><return_keys>N</return_keys><schema>{target_schema}</schema><specify_fields>Y</specify_fields><table>{target_table}</table><tablename_in_field>N</tablename_in_field><tablename_in_table>Y</tablename_in_table><truncate>N</truncate><use_batch>Y</use_batch><attributes/><GUI><xloc>960</xloc><yloc>160</yloc></GUI></transform><transform_error_handling></transform_error_handling><attributes/></pipeline>'''
 xml=_apply_target(xml,task);path.write_text(xml,encoding='utf-8');checksum=hashlib.sha256(path.read_bytes()).hexdigest();transforms=['CSVInput','FilterRows','SimpleMapping' if module_path else 'Calculator','SortRows','GroupBy','TableOutput'];return {'path':str(path),'version':version,'checksum':checksum,'size':path.stat().st_size,'columns':output_columns,'source_columns':columns,'transforms':transforms,'aggregation':agg,'module_path':str(module_path) if module_path else None,'generation_plan':generation_plan(task)}

def build_postgres_hpl(task:dict,columns:list[str]):
 task_dir=ROOT/'hop-project'/'pipelines'/task['id'];task_dir.mkdir(parents=True,exist_ok=True)
 existing=list(task_dir.glob('pipeline-v*.hpl'));version=max([int(p.stem.rsplit('v',1)[1]) for p in existing]+[0])+1;path=task_dir/f'pipeline-v{version}.hpl'
 configured=task['source_config'].get('sources') or []
 source_schema=_safe_ident((configured[0] if configured else task['source_config'])['schema']);source_table=_safe_ident((configured[0] if configured else task['source_config'])['table']);target_schema=escape(task['target_config']['schema']);target_table=escape(task['target_config']['table'])
 if task['source_config'].get('query'):
  output_columns=columns;query=escape(task['source_config']['query'].strip().rstrip(';'))
 elif source_schema=='poc_source' and source_table=='demo_customer_orders':
  output_columns=['order_id','customer_id','order_date','amount_twd','source_currency','order_status']
  query='SELECT order_id, customer_id, order_date, amount AS amount_twd, currency AS source_currency, status AS order_status FROM poc_source.demo_customer_orders WHERE status &lt;&gt; \'CANCELLED\' ORDER BY order_id LIMIT 10'
 else:
  output_columns=columns;query=f'SELECT * FROM {source_schema}.{source_table} LIMIT 10'
 mappings=''.join(f'<field><column_name>{escape(c)}</column_name><stream_name>{escape(c)}</stream_name></field>' for c in output_columns)
 xml=f'''<?xml version="1.0" encoding="UTF-8"?><pipeline><info><name>{escape(task['id'])}-postgresql-postgresql</name><name_sync_with_filename>N</name_sync_with_filename><description>Generated PostgreSQL table pipeline</description><extended_description/><pipeline_version>{version}</pipeline_version><pipeline_type>Normal</pipeline_type><parameters></parameters><capture_transform_performance>N</capture_transform_performance><transform_performance_capturing_delay>1000</transform_performance_capturing_delay><transform_performance_capturing_size_limit>100</transform_performance_capturing_size_limit><created_user>ai-agents-poc</created_user><created_date>2026/08/05 00:00:00.000</created_date><modified_user>ai-agents-poc</modified_user><modified_date>2026/08/05 00:00:00.000</modified_date><key_for_session_key/><is_key_private>N</is_key_private></info><notepads></notepads><order><hop><from>Read PostgreSQL</from><to>PostgreSQL Output</to><enabled>Y</enabled></hop></order><transform><name>Read PostgreSQL</name><type>TableInput</type>{STEPS_BASE}<connection>ai-agents-poc</connection><execute_each_row>N</execute_each_row><limit>10</limit><lookup/><sql>{query}</sql><variables_active>Y</variables_active><attributes/><GUI><xloc>100</xloc><yloc>160</yloc></GUI></transform><transform><name>PostgreSQL Output</name><type>TableOutput</type>{STEPS_BASE}<commit>10</commit><connection>ai-agents-poc</connection><fields>{mappings}</fields><ignore_errors>N</ignore_errors><partitioning_daily>N</partitioning_daily><partitioning_enabled>N</partitioning_enabled><partitioning_monthly>N</partitioning_monthly><return_keys>N</return_keys><schema>{target_schema}</schema><specify_fields>Y</specify_fields><table>{target_table}</table><tablename_in_field>N</tablename_in_field><tablename_in_table>Y</tablename_in_table><truncate>N</truncate><use_batch>Y</use_batch><attributes/><GUI><xloc>400</xloc><yloc>160</yloc></GUI></transform><transform_error_handling></transform_error_handling><attributes/></pipeline>'''
 xml=_apply_target(xml,task);path.write_text(xml,encoding='utf-8');checksum=hashlib.sha256(path.read_bytes()).hexdigest()
 return {'path':str(path),'version':version,'checksum':checksum,'size':path.stat().st_size,'columns':output_columns,'source_columns':columns,'transforms':['TableInput','TableOutput'],'generation_plan':generation_plan(task)}

def build_vertica_query_hpl(task:dict,columns:list[str]):
 cfg=task['source_config'];raw=cfg.get('query','').strip().rstrip(';')
 if not re.match(r'(?is)^(select|with)\b',raw) or ';' in raw or re.search(r'(?is)\b(insert|update|delete|drop|alter|truncate|create|grant|revoke|copy|call)\b',raw):raise ValueError('Vertica query must be one read-only SELECT/WITH')
 output=cfg.get('output_fields') or columns
 output=[_safe_ident(x['name'] if isinstance(x,dict) else x) for x in output]
 task_dir=ROOT/'hop-project'/'pipelines'/task['id'];task_dir.mkdir(parents=True,exist_ok=True);existing=list(task_dir.glob('pipeline-v*.hpl'));version=max([int(p.stem.rsplit('v',1)[1]) for p in existing]+[0])+1;path=task_dir/f'pipeline-v{version}.hpl'
 mappings=''.join(f'<field><column_name>{escape(c)}</column_name><stream_name>{escape(c)}</stream_name></field>' for c in output);target_schema=escape(task['target_config']['schema']);target_table=escape(task['target_config']['table']);query=escape(raw)
 xml=f'''<?xml version="1.0" encoding="UTF-8"?><pipeline><info><name>{escape(task['id'])}-vertica-complex-query</name><name_sync_with_filename>N</name_sync_with_filename><description>Vertica SQL pushdown preserving canonical logical graph</description><extended_description/><pipeline_version>{version}</pipeline_version><pipeline_type>Normal</pipeline_type><parameters></parameters><capture_transform_performance>N</capture_transform_performance><created_user>ai-agents-poc</created_user><created_date>2026/08/13 00:00:00.000</created_date><modified_user>ai-agents-poc</modified_user><modified_date>2026/08/13 00:00:00.000</modified_date></info><notepads></notepads><order><hop><from>Vertica Complex SQL</from><to>Vertica Output</to><enabled>Y</enabled></hop></order><transform><name>Vertica Complex SQL</name><type>TableInput</type>{STEPS_BASE}<connection>vertica-poc</connection><execute_each_row>N</execute_each_row><limit>10</limit><lookup/><sql>{query}</sql><variables_active>Y</variables_active><attributes/><GUI><xloc>100</xloc><yloc>160</yloc></GUI></transform><transform><name>Vertica Output</name><type>TableOutput</type>{STEPS_BASE}<commit>10</commit><connection>vertica-poc</connection><fields>{mappings}</fields><ignore_errors>N</ignore_errors><return_keys>N</return_keys><schema>{target_schema}</schema><specify_fields>Y</specify_fields><table>{target_table}</table><tablename_in_field>N</tablename_in_field><tablename_in_table>Y</tablename_in_table><truncate>N</truncate><use_batch>Y</use_batch><attributes/><GUI><xloc>450</xloc><yloc>160</yloc></GUI></transform><transform_error_handling></transform_error_handling><attributes/></pipeline>'''
 path.write_text(xml,encoding='utf-8');checksum=hashlib.sha256(path.read_bytes()).hexdigest()
 return {'path':str(path),'version':version,'checksum':checksum,'size':path.stat().st_size,'columns':output,'source_columns':columns,'transforms':['TableInput','TableOutput'],'sql_pushdown':True,'query':raw,'generation_plan':generation_plan(task)}

def build_stage_hwf(task:dict,columns:list[str]):
 cfg=task['target_config'];mode=str(cfg.get('stage_mode')).upper();schema=_safe_ident(cfg['schema']);table=_safe_ident(cfg['table']);source=(task.get('source_config',{}).get('sources') or [{}])[0];raw_fields=source.get('fields') or [{'name':x,'type':'VARCHAR(255)'} for x in columns];fields=[x for x in raw_fields if str(x.get('name') or '').strip() and str(x.get('type') or '').strip()]
 definitions=[]
 for item in fields:
  name=_safe_ident(item['name']);kind=_vertica_type(item.get('type') or 'VARCHAR(255)');definitions.append(f'"{name}" {kind}')
 def safe_path(value):
  value=str(value or '')
  if not value.startswith('/') or any(x in value for x in ("'",';','\n','\r')):raise ValueError('Vertica data/reject/exception path must be an absolute server path')
  return value
 data_path=safe_path(cfg.get('data_path'));reject_path=safe_path(cfg.get('reject_path'));exception_path=safe_path(cfg.get('exception_path'))
 if mode=='EXTERNAL':
  if not fields:raise ValueError('External Table requires source field names and Vertica types')
  delimiter=str(cfg.get('delimiter') or ',');quote=str(cfg.get('quote') or '"')
  if len(delimiter)!=1 or delimiter in "';\n\r" or len(quote)!=1 or quote in "';\n\r":raise ValueError('Unsafe CSV delimiter or quote')
  ddl=f'''CREATE EXTERNAL TABLE IF NOT EXISTS "{schema}"."{table}"\n(\n  {',\n  '.join(definitions)}\n)\nAS COPY FROM '{data_path}' DELIMITER '{delimiter}' ENCLOSED BY '{quote}' SKIP {1 if cfg.get('header',True) else 0}\nREJECTED DATA '{reject_path}' EXCEPTIONS '{exception_path}';'''
 else:
  parser='fjsonparser()' if str(cfg.get('format','JSON')).upper()=='JSON' else "fdelimitedparser(header=true)"
  ddl=f'''CREATE FLEX TABLE IF NOT EXISTS "{schema}"."{table}"();\nCOPY "{schema}"."{table}" FROM '{data_path}' PARSER {parser}\nREJECTED DATA '{reject_path}' EXCEPTIONS '{exception_path}';'''
 task_dir=ROOT/'hop-project'/'workflows'/task['id'];task_dir.mkdir(parents=True,exist_ok=True);existing=list(task_dir.glob('stage-v*.hwf'));version=max([int(p.stem.rsplit('v',1)[1]) for p in existing]+[0])+1;path=task_dir/f'stage-v{version}.hwf';sql_xml=escape(ddl)
 xml=f'''<?xml version="1.0" encoding="UTF-8"?><workflow><name>{escape(task['id'])}-{mode.lower()}</name><name_sync_with_filename>N</name_sync_with_filename><description>Generated Stage {mode} workflow</description><workflow_version>{version}</workflow_version><job_status>0</job_status><directory>/</directory><parameters/><pass_batchid>N</pass_batchid><actions><action><name>Start</name><type>SPECIAL</type><repeat>N</repeat><schedulerType>0</schedulerType><parallel>N</parallel><xloc>100</xloc><yloc>100</yloc></action><action><name>Create {mode} Table</name><type>SQL</type><sql>{sql_xml}</sql><useVariableSubstitution>T</useVariableSubstitution><sqlfromfile>F</sqlfromfile><sendOneStatement>F</sendOneStatement><connection>vertica-poc</connection><parallel>N</parallel><xloc>300</xloc><yloc>100</yloc></action><action><name>Success</name><type>SUCCESS</type><parallel>N</parallel><xloc>520</xloc><yloc>100</yloc></action></actions><hops><hop><from>Start</from><to>Create {mode} Table</to><enabled>Y</enabled><evaluation>Y</evaluation><unconditional>Y</unconditional></hop><hop><from>Create {mode} Table</from><to>Success</to><enabled>Y</enabled><evaluation>Y</evaluation><unconditional>N</unconditional></hop></hops><notepads/><attributes/></workflow>'''
 path.write_text(xml,encoding='utf-8');checksum=hashlib.sha256(path.read_bytes()).hexdigest();return {'path':str(path),'artifact_type':'HWF','version':version,'checksum':checksum,'size':path.stat().st_size,'columns':[x['name'] for x in fields],'transforms':['SQL'],'stage_mode':mode,'sql':ddl,'generation_plan':generation_plan(task)}

def static_validate(artifact:dict):
 if str(artifact.get('artifact_type','HPL')).upper()=='HWF':
  root=ET.parse(artifact['path']).getroot();actions=root.findall('actions/action');types=[x.findtext('type') for x in actions];statement=artifact.get('sql','');errors=[]
  if root.tag!='workflow':errors.append('Root element must be workflow')
  if 'SQL' not in types or 'SPECIAL' not in types or 'SUCCESS' not in types:errors.append('Workflow must contain Start, SQL and Success actions')
  if not re.match(r'(?is)^CREATE\s+(EXTERNAL\s+TABLE|FLEX\s+TABLE)',statement.strip()):errors.append('Stage DDL must create only External or Flex Table')
  if re.search(r'(?is)\b(DROP|ALTER|GRANT|REVOKE|DELETE|UPDATE)\b',statement):errors.append('Unsafe SQL keyword in Stage DDL')
  return {'valid':not errors,'errors':errors,'action_types':types,'xml_well_formed':True,'sql':statement,'stage_mode':artifact.get('stage_mode')}
 root=ET.parse(artifact['path']).getroot();types=[x.findtext('type') for x in root.findall('transform')];names=[x.findtext('name') for x in root.findall('transform')]
 errors=[]
 if root.tag!='pipeline':errors.append('Root element must be pipeline')
 required=('CSVInput','FilterRows','TableOutput') if 'CSVInput' in types else ('TableInput','TableOutput')
 for item in required:
  if item not in types:errors.append(f'Missing transform {item}')
 if len(names)!=len(set(names)):errors.append('Transform names must be unique')
 errors.extend(validate_pipeline_graph(root))
 return {'valid':not errors,'errors':errors,'transform_types':types,'transform_names':names,'xml_well_formed':True,'generation_plan':artifact.get('generation_plan')}

def semantic_validate(task:dict,artifact:dict):
 errors=[]
 if len(artifact['columns'])<1:errors.append('No source columns')
 if not task['target_config'].get('schema') or not task['target_config'].get('table'):errors.append('Target schema/table missing')
 return {'valid':not errors,'errors':errors,'policy':'FIRST_10_VALID_ROWS','max_rows':10,'post_write_count':True,'source_columns':artifact['columns'],'target':task['target_config']}

def persist_artifact(db_url:str,task_id:str,artifact:dict):
 artifact_id=uuid.uuid4();primary=Path(artifact['path'])
 related=[]
 for key in ('module_path','workflow_path','hwf_path'):
  value=artifact.get(key)
  if value:related.append(Path(value))
 for key in ('module_paths','workflow_paths','artifact_paths'):
  related.extend(Path(x) for x in (artifact.get(key) or []))
 with psycopg.connect(db_url) as conn:
  with conn.cursor() as cur:
   cur.execute("update platform.hop_artifact set is_current=false where task_id=%s",(task_id,))
   primary_type=str(artifact.get('artifact_type') or ('HWF' if primary.suffix.lower()=='.hwf' else 'HPL')).upper()
   cur.execute("insert into platform.hop_artifact(artifact_id,task_id,artifact_type,version,file_path,checksum,file_size,is_current) values(%s,%s,%s,%s,%s,%s,%s,true)",(artifact_id,task_id,primary_type,artifact['version'],str(primary),artifact['checksum'],artifact['size']))
   seen={str(primary.resolve()).lower()}
   for path in related:
    resolved=str(path.resolve()).lower()
    if resolved in seen or not path.is_file():continue
    seen.add(resolved);child_id=uuid.uuid4();kind='HWF' if path.suffix.lower()=='.hwf' else 'HPL';checksum=hashlib.sha256(path.read_bytes()).hexdigest()
    cur.execute("insert into platform.hop_artifact(artifact_id,task_id,artifact_type,version,parent_artifact_id,file_path,checksum,file_size,is_current) values(%s,%s,%s,%s,%s,%s,%s,%s,true)",(child_id,task_id,kind,artifact['version'],artifact_id,str(path),checksum,path.stat().st_size))
 return str(artifact_id)

def persist_validation(db_url:str,task_id:str,kind:str,result:dict):
 with psycopg.connect(db_url) as conn:
  conn.execute("insert into platform.validation_run(validation_run_id,task_id,validation_type,status,validation_result,report_text) values(%s,%s,%s,%s,%s,%s)",(uuid.uuid4(),task_id,kind,'SUCCEEDED' if result['valid'] else 'FAILED',json.dumps(result),json.dumps(result,ensure_ascii=False)))

def _safe_ident(value:str):
 if not re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*',value):raise ValueError(f'Unsafe SQL identifier: {value}')
 return value

def table_count(db_url:str,target:dict):
 schema=_safe_ident(target['schema']);table=_safe_ident(target['table'])
 if (target.get('type') or 'POSTGRESQL').upper()=='VERTICA':
  import vertica_python
  cfg={'host':os.getenv('VERTICA_HOST','127.0.0.1'),'port':int(os.getenv('VERTICA_PORT','5433')),'user':os.getenv('VERTICA_USER','dbadmin'),'password':os.getenv('VERTICA_PASSWORD',''),'database':os.getenv('VERTICA_DATABASE',''),'tlsmode':os.getenv('VERTICA_TLSMODE','disable')}
  with vertica_python.connect(**cfg) as conn:
   try:cur=conn.cursor();cur.execute(f'SELECT COUNT(*) FROM "{schema}"."{table}"');return cur.fetchone()[0]
   except Exception:return 0
 with psycopg.connect(db_url) as conn:return conn.execute(sql.SQL('select count(*) from {}.{}').format(sql.Identifier(schema),sql.Identifier(table))).fetchone()[0]

def execute_hop(db_url:str,task:dict,artifact:dict,artifact_id:str):
 hop=ROOT/'hop';metadata_dir=hop/'config'/'projects'/'default'/'metadata'/'rdbms';metadata_dir.mkdir(parents=True,exist_ok=True);metadata_file=metadata_dir/'ai-agents-poc.json';vertica_metadata_file=metadata_dir/'vertica-poc.json'
 metadata={'rdbms':{'POSTGRESQL':{'databaseName':'ai_agents','pluginId':'POSTGRESQL','accessType':0,'hostname':'127.0.0.1','password':os.getenv('POSTGRES_PASSWORD','postgres'),'pluginName':'PostgreSQL','port':'5432','attributes':{'SUPPORTS_BOOLEAN_DATA_TYPE':'Y','QUOTE_ALL_FIELDS':'N','EXTRA_OPTION_POSTGRESQL.characterEncoding':'UTF-8','EXTRA_OPTION_POSTGRESQL.charSet':'UTF-8','EXTRA_OPTION_POSTGRESQL.client_encoding':'UTF8'},'username':'postgres'}},'name':'ai-agents-poc'}
 vertica_host=os.getenv('VERTICA_HOST','127.0.0.1');vertica_port=os.getenv('VERTICA_PORT','5433');vertica_database=os.getenv('VERTICA_DATABASE','VMart') or 'VMart'
 vertica_metadata={'rdbms':{'GENERIC':{'databaseName':vertica_database,'pluginId':'GENERIC','accessType':0,'hostname':vertica_host,'password':os.getenv('VERTICA_PASSWORD',''),'pluginName':'Generic database','port':vertica_port,'manualUrl':f'jdbc:vertica://{vertica_host}:{vertica_port}/{vertica_database}','attributes':{'CUSTOM_DRIVER_CLASS':'com.vertica.jdbc.Driver','DATABASE_DIALECT_ID':'VERTICA','QUOTE_ALL_FIELDS':'N'},'username':os.getenv('VERTICA_USER','dbadmin')}},'name':'vertica-poc'}
 metadata_file.write_text(json.dumps(metadata),encoding='utf-8');vertica_metadata_file.write_text(json.dumps(vertica_metadata),encoding='utf-8');before=table_count(db_url,task['target_config']);started=time.monotonic();run_id=uuid.uuid4()
 command=[os.environ.get('COMSPEC',r'C:\Windows\System32\cmd.exe'),'/d','/c',str(hop/'hop-run.bat'),'-j','default','-r','local','-f',artifact['path'],'-l','BASIC']
 try:
  run_env=os.environ.copy();run_env['JAVA_TOOL_OPTIONS']='-Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8'
  result=subprocess.run(command,cwd=hop,capture_output=True,text=True,encoding='utf-8',errors='replace',timeout=180,env=run_env)
 finally:
  metadata_file.unlink(missing_ok=True);vertica_metadata_file.unlink(missing_ok=True)
 duration=round((time.monotonic()-started)*1000);after=table_count(db_url,task['target_config']);written=max(0,after-before)
 detail={'exit_code':result.returncode,'stdout':result.stdout[-12000:],'stderr':result.stderr[-12000:],'before_count':before,'after_count':after,'rows_written':written,'duration_ms':duration,'command':[str(x) for x in command[3:]]}
 with psycopg.connect(db_url) as conn:
  conn.execute("insert into platform.hop_run(hop_run_id,task_id,hpl_artifact_id,status,command_line,parameters,exit_code,rows_written,post_write_count,started_at,ended_at,duration_ms,error_detail) values(%s,%s,%s,%s,%s,%s,%s,%s,%s,now()-(%s * interval '1 millisecond'),now(),%s,%s)",(run_id,task['id'],artifact_id,'SUCCEEDED' if result.returncode==0 else 'FAILED',' '.join(detail['command']),json.dumps({}),result.returncode,written,after,duration,duration,json.dumps({} if result.returncode==0 else detail)))
 return detail
